Add a section explaining how to get an API key from The Guardian Open Platform
nikhilbansal97/World-Now pull request #16
Opened 2018-10-03 08:01 UTC by rosariopfernandes

resolves #10

2018-10-03 09:12 UTC, NalediMadlopha requested changes
We should not be storing the API key in the `build.gradle` file because we are working on a public repo and you do not want your to expose your API key to the public.

My suggestion and as the project is setup you need to store the API key in the `~/.gradle/gradle.properties` file which is located in your home directory. Add a field `Guardian_ApiKey="ENTER_YOUR_API_KEY_HERE"` in this file then rebuild the project, a `BuildConfig` file with be generated with a field called `ApiKey` because of this line `buildConfigField 'String', "ApiKey", Guardian_ApiKey` in the app module `build.gradle` file. Then the `ApiKey` field can be used in the source code. This way even when you push code in the project the API key will not be pushed because it is not directly part of the project, it is stored in a global Gradle file in your home directory.

2018-10-05 09:36 UTC, rosariopfernandes commented
@NalediMadlopha Somehow I missed your comment when it was created, my bad.
I didn't know we could create variables on the `gradle.properties` file, TIL! Thanks for the feedback, I've made the suggested changes.

2018-10-05 11:44 UTC, NalediMadlopha approved these changes
Just a side note; please checkout this [link](https://chris.beams.io/posts/git-commit/#imperative) on writing good commit messages. "Make suggested changes" is not so descriptive and because you are making changes based on a PR, you can squish your commit to be part of the your first commit using `git rebase`.

2018-10-05 12:01 UTC, rosariopfernandes commented
@NalediMadlopha :smiley: That wil be helpful. Thank you very much!

2018-10-05 16:02 UTC, ppiliar requested changes
Instructions looks good to me, just 2 small issues.

2018-10-05 16:02 UTC, ppiliar commented on README.md
> +5. Open your `gradle.properties` file in a text editor. On Windows, it's usually located at
I think there should be explicitly stated that we mean **global** gradle.properties file to avoid misunderstanding.

2018-10-05 16:02 UTC, ppiliar commented on README.md
> + you'll need an API Key. Follow these 5 steps to obtain your key:
There you say Follow these 5 steps, but there is 6 steps in total.

2018-10-05 17:35 UTC, rosariopfernandes commented
Thanks @ppiliar !

2018-10-05 19:25 UTC, ppiliar approved these changes

2018-10-06 09:56 UTC, merged

2018-10-06 09:56 UTC, nikhilbansal97 commented
@rosariopfernandes Awesome job! 👍